services:
  - type: web
    name: cad-portfolio-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RECIPIENT_EMAIL
        sync: false
